# Generated by Django 4.1.4 on 2022-12-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('svg2font', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
